import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Locale } from "@/i18n/dictionaries";
import { ColorScheme } from "@/interface/theme.interface";
import type {
  SidebarState,
  SidebarVariant,
  SidebarSide,
} from "@/interface/theme.interface";
import RootProvider from "@/components/provider";
import type { ThemeMode } from "@/interface/theme.interface";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ lang: Locale }>
}>) {
  const { lang } = await params;
  const defaultThemeMode: ThemeMode = "system";
  const defaultSidebarState: SidebarState = "expanded";
  const defaultSidebarVariant: SidebarVariant = "sidebar";
  const defaultSidebarSide: SidebarSide = "left";

  return (
    <html
      lang={lang}
      suppressHydrationWarning
      data-color-scheme={ColorScheme.Default}
      data-sidebar-state={defaultSidebarState}
      data-sidebar-variant={defaultSidebarVariant}
      data-sidebar-side={defaultSidebarSide}
    >
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased w-full h-screen overflow-hidden`}
      >

          <RootProvider
            defaultThemeMode={defaultThemeMode}
            defaultColorScheme={ColorScheme.Default}
            defaultLocale={lang}
            defaultSidebarState={defaultSidebarState}
            defaultSidebarVariant={defaultSidebarVariant}
            defaultSidebarSide={defaultSidebarSide}
          >
            {children}
          </RootProvider>
      </body>
    </html>
  );
}
