import "./globals.css";
import type {
	SidebarState,
	SidebarVariant,
	SidebarSide,
} from "@/interface/theme.interface";
import type { Metadata } from "next";
import { Toaster } from "@/components/ui/sonner";
import { Locale, locales } from "@/i18n/dictionaries";
import { Geist, Geist_Mono } from "next/font/google";
import { ColorScheme } from "@/interface/theme.interface";
import type { ThemeMode } from "@/interface/theme.interface";
import { AppContent } from "@/components/provider/app-content";
import { ThemeProvider } from "@/components/provider/theme-provider/theme-provider";
import { UserSessionProvider } from "@/components/provider/user-session-provider/user-session-provider";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export function generateStaticParams() {
	return locales.map((lang) => ({ lang }));
}

export default async function RootLayout({
	children,
	params,
}: Readonly<{
	children: React.ReactNode;
	params: Promise<{ lang: string }>;
}>) {
	const { lang: langParam } = await params;
	const lang = (
		locales.includes(langParam as Locale) ? langParam : locales[0]
	) as Locale;
	const defaultThemeMode: ThemeMode = "system";
	const defaultSidebarState: SidebarState = "expanded";
	const defaultSidebarVariant: SidebarVariant = "sidebar";
	const defaultSidebarSide: SidebarSide = "left";

	return (
		<html lang={lang} suppressHydrationWarning={true}>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased w-full h-screen overflow-hidden`}
			>
				<ThemeProvider
					defaultThemeMode={defaultThemeMode}
					defaultColorScheme={ColorScheme.Default}
					defaultLocale={lang}
					defaultSidebarState={defaultSidebarState}
					defaultSidebarVariant={defaultSidebarVariant}
					defaultSidebarSide={defaultSidebarSide}
				>
					<UserSessionProvider>
						<AppContent>{children}</AppContent>
					</UserSessionProvider>
				</ThemeProvider>
				<Toaster position="bottom-right" richColors />
			</body>
		</html>
	);
}
